config/executables.go
dev.flow
docs/config/executables.md
docs/docs.flow
tests/testdata/debugging.flow
tests/testdata/happy-path.flow
tests/testdata/sample.flow.tmpl

This is a breaking change that removed the `type` field from the exec configurations. Instead, the exec type can be defined inline. This change was made to make configuring simpler
- `type` exec field is now an inline field and does not need to be specified in yaml

(feat) move exec type field config to inline

---

cmd/internal/exec.go
cmd/internal/get.go
cmd/internal/interactive/interactive.go
cmd/internal/library.go
cmd/internal/list.go
config/executables.go
config/workspace_config.go
go.mod
go.sum
internal/io/executable/views.go
internal/io/library/library.go
internal/io/library/update.go
internal/io/library/view.go

This pr makes it so that the `r` key can be used to run the selected executable in the library and get/list exec views.
- Small code refactoring of the library and exec command. Library is now launch as a tuikit container frame so that it can be killed 
- `r` callback keys added for the get and list exec and library commands.
- Fixed a bug with selecting executables in the list view. Now the ref is used as a consistent ID

(feat) run executables from interactive views

---

config/cache/executable_generator.go
config/cache/executables_cache.go

The ws and definition context wasn't being set on generated executables, resulting in errors when running them. This commit pushed down that information when the generated executables are added to the cache

(fix) set context on generated execs

---

config/executable_md.go
config/workspace_config.go
examples/render.flow
go.mod
go.sum
internal/io/library/init.go
internal/io/library/library.go
internal/io/library/styles.go
internal/io/library/update.go
internal/io/library/view.go

Use the `tab` key to switch the library's view layout (3 pane split vs 2/1 pane split). This includes a couple other related fixes which incorporates tuikit frame updates, help menu updates, and format key updates.
- By default, the library opens with just the ws and exec list panes. The tab key can toggle showing the exec documentation view alongside then. When not in that mode, enter or the -> arrow can be used to select an exec from a list
- Remove library loading model since tuikit will provide one
- Set library size on init and let tuikit handle resizing more naturally

(feat) toggle library pane splitting

---

types/executable/executable.go
types/executable/executables_test.go

Filter listed executables by their aliases in addition to their ref and description
- Listing executables with ```flow list executables -f STRING``` now additionally searches the aliases values and returns any executables with aliases that contain the filter string

(fix) Include aliases in -f filtering #139

---

go.mod
go.sum
types/executable/executable_md.go

Small fix for the markdown formatting of executables when a request exec is being transformed.
Additionally bumps tuikit to fix a small bug with debug logs introduced in the last commit

(fix) exec markdown formatting for transformed req

---

cmd/internal/flags/types.go
cmd/internal/library.go
docs/cli/flow_library.md
docs/cli/flow_library_glance.md
internal/cache/executables_cache.go
internal/context/context.go
internal/io/library/init.go
internal/io/library/styles.go
internal/io/library/view.go
tests/utils/sub_execs.go
types/executable/executable.go
types/executable/ref.go

By default only show executables in the root namespace with options to show all namespaces. Includes improvements for ref displays in the library view.

feat: add library flag for all ns filtering

---

cmd/internal/config.go
cmd/internal/workspace.go
docs/cli/flow_config_set.md
docs/cli/flow_workspace.md
docs/cli/flow_workspace_create.md
docs/cli/flow_workspace_set.md
docs/development.md
docs/quickstart.md
tests/workspace_cmds_e2e_test.go

Additional test coverage that comes with a couple subcommand updates:
- `flow workspace new` -> `flow workspace create` 
- `flow config set workspace` -> `flow workspace set`

test!: create ws e2e tests with subcommand updates

---

cmd/internal/config.go
cmd/internal/exec.go
cmd/internal/flags/types.go
cmd/internal/helpers.go
cmd/internal/library.go
cmd/internal/secret.go
cmd/internal/workspace.go
docs/cli/flow_config_set.md
docs/cli/flow_config_set_notifications.md
docs/cli/flow_config_set_theme.md
docs/cli/flow_config_set_timeout.md
docs/guide/interactive.md
docs/guide/templating.md
docs/schemas/config_schema.json
docs/types/config.md
go.mod
go.sum
internal/context/context.go
internal/io/styles.go
internal/templates/form.go
tests/utils/context.go
types/config/config.gen.go
types/config/config.go
types/config/schema.yaml
types/executable/executable.go

Introduces theme customization a new config subcommand, toggling of notifications via a subcommand, and changing the default timeout via a subcommand

feat: more customization commands

---

internal/runner/parallel/parallel.go
internal/runner/serial/serial.go

This "fixes" a panic that happens if the cmd or ref isn't defined for a serial or parallel exec

fix: return error on invalid ref config

---

docs/guide/interactive.md
docs/schemas/config_schema.json
docs/types/config.md
internal/context/context.go
internal/context/context_test.go
types/config/config.gen.go
types/config/schema.yaml

Adds the `colorOverride` field to the user config file. This allows overriding the lipgloss colors used in the TUI's theme

feat: add config fields for overriding theme colors

---

types/executable/executable.go
types/executable/executable_md.go
types/workspace/workspace.go
types/workspace/workspace_md.go

* Introduced `enrichedExecutable` and `enrichedWorkspace` structs to encapsulate additional metadata (e.g., `FullDescription`, `Namespace`, `Path`) for better YAML/JSON serialization. 
* Added custom `MarshalJSON` and `UnmarshalJSON` methods for `Executable` and `RequestExecutableType` to handle timeout serialization/deserialization as strings, ensuring compatibility with JSON formats (`types/executable/executable.go`).

refactor: include all ws and exec data in json

---

docs/schemas/flowfile_schema.json
docs/types/flowfile.md
internal/cache/executable_generator.go
internal/runner/runner.go
internal/runner/runner_test.go
tools/builder/exec.go
types/executable/executable.gen.go
types/executable/executable.go
types/executable/executable_md.go
types/executable/executable_schema.yaml

Removed the default value (`30m0s`) for the `Timeout` field in `flowfile_schema.json` and `flowfile.md`. This aligns with the new approach of treating `Timeout` as optional.

refactor: remove the default timeout for executables

---

cmd/internal/flags/types.go
docs/cli/flow_exec.md
internal/services/run/run.go
internal/utils/utils.go
tests/secret_cmds_e2e_test.go
tests/utils/context.go

A couple of small fixes for the GH action

fix: log output in CI

---

.execs/validate.flow
desktop/src-tauri/src/types/generated/flowfile.rs
desktop/src/pages/Executable/types/ExecutableLaunchDetails.tsx
desktop/src/types/generated/flowfile.ts
docs/schemas/flowfile_schema.json
docs/types/flowfile.md
go.mod
go.sum
internal/io/common/common.go
internal/io/library/update.go
internal/io/workspace/views.go
internal/runner/launch/launch.go
internal/services/open/exec.go
internal/services/open/exec_darwin.go
internal/services/open/exec_windows.go
internal/services/open/open.go
internal/services/open/open_test.go
types/executable/executable.gen.go
types/executable/executable_md.go
types/executable/executable_schema.yaml

Drops the useless `wait` option for launch execs, moves the logic into the flow codebase, and fixes an issue with launching http uris.

fix: launch shouldn't expand http uris

---

go.mod
go.sum
internal/io/library/view.go

Bumps tuikit to fix some post-run output issues and adds changes the icon that's used in the exec list for public executables / executables within the current ws. This should hopefully make it a bit clearer as to what can be run and what can't from the current context.

feat: add different icon for runnable execs in the library

---

types/executable/executables_test.go
types/executable/flowfile.go
types/executable/template.go

Fixes a small bug that was causing sync to pick up on files that ended with `.flow` + something else (i.e. `.flow.tmpl`)

fix: expected flowfile extensions must have right suffix

---

cmd/internal/flags/types.go
cmd/internal/vault.go
docs/cli/flow_vault_create.md
docs/guide/first-workflow.md
docs/guide/secrets.md
internal/io/vault/view.go
internal/vault/v2/vault.go
tests/secret_cmds_e2e_test.go

A variety of changes that improves the experience of creating a vault. Includes the `--set` flag, a clean way of getting the generated token, and some docs updates

fix: improve vault setup experience

---

.execs/build.flow
README.md
desktop/src-tauri/src/types/generated/template.rs
desktop/src/types/generated/template.ts
docs/README.md
docs/_coverpage.md
docs/cli/flow_browse.md
docs/cli/flow_exec.md
docs/guide/README.md
docs/guide/advanced.md
docs/index.html
docs/schemas/template_schema.json
docs/types/template.md
internal/io/output.go
internal/mcp/prompts.go
internal/mcp/resources/template_schema.json
tests/utils/builder/exec.go
types/executable/template.gen.go
types/executable/template_schema.yaml

Change docsify routing for better SEO / AI support.

docs: switch to history router

---

cmd/internal/exec.go
desktop/src-tauri/src/types/generated/flowfile.rs
desktop/src-tauri/src/types/generated/workspace.rs
desktop/src/types/generated/flowfile.ts
desktop/src/types/generated/workspace.ts
docs/guide/executables.md
docs/guide/workspaces.md
docs/schemas/flowfile_schema.json
docs/schemas/workspace_schema.json
docs/types/flowfile.md
docs/types/workspace.md
internal/mcp/resources/flowfile_schema.json
internal/mcp/resources/workspace_schema.json
internal/utils/env/env.go
internal/utils/env/env_test.go
tests/exec_cmd_e2e_test.go
tests/utils/builder/exec.go
tests/utils/builder/flowfile.go
types/executable/executable.gen.go
types/executable/executable_schema.yaml
types/workspace/schema.yaml
types/workspace/workspace.gen.go

This pull request adds support for loading environment variables from `.env` files at both the workspace and executable parameter levels. It introduces new configuration options, updates documentation and schemas, and includes comprehensive tests for the new functionality.

feat: add support for env files at ws and exec level

---

internal/utils/utils.go
internal/utils/utils_test.go

Small fix that prevents environment variable for directory / file path fields. When `//` is used as a prefix, expansion was previously being skipped.

fix: environment variables should be expanded when ws dir prefix x is used

---

cmd/internal/browse.go
cmd/internal/flags/types.go
docs/cli/flow_browse.md
internal/io/library/init.go
internal/io/library/library.go
types/common/common.go
types/executable/executable.go
types/executable/executables_test.go

Add support for filtering executables by visibility. This will allow the inclusion of internal and hidden executables in the output when the flag is set to those values. The returned executables use a hierarchical match instead of exact (i.e. internal will also return private and public)

feat: visibility flag for browse cmd
